test-3

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,40 +29,34 @@ jobs:
         run: |
           npm run test
 
-          check-branch-name:
-            runs-on: ubuntu-latest
-            steps:
-              - name: Checkout code
-                uses: actions/checkout@v2
-        
-              - name: Check branch name on push
-                if: github.event_name == 'push'
-                run: |
-                  branch_name=$(git symbolic-ref --short HEAD)
-                  echo "Current branch: $branch_name"
-                  if [[ ! "$branch_name" =~ ^feature/.* ]]; then
-                    echo "❌ Invalid branch name. The branch name must start with 'feature/'"
-                    exit 1
-                  fi
-                  echo "✅ The branch name is correct: $branch_name"
-        
-              - name: Check source branch on pull request
-                if: github.event_name == 'pull_request'
-                run: |
-                  branch_name="${{ github.head_ref }}"
-                  echo "🔍 Checking the branch: $branch_name"
-                  if [[ "$branch_name" == "test" ]]; then
-                    echo "❌ DENIED: You cannot send PR from test to main."
-                    exit 1
-                  fi
-                  echo "✅ The branch is allowed: $branch_name"
-        
-              - name: Fail PR if branch is invalid
-                if: failure()
-                run: |
-                  echo "❌ This PR violates branch rules."
-                  exit 1
-        
+  check-branch-name:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Check branch name on push
+        if: github.event_name == 'push'
+        run: |
+          branch_name=$(git symbolic-ref --short HEAD)
+          echo "Current branch: $branch_name"
+          if [[ ! "$branch_name" =~ ^feature/.* ]]; then
+            echo "❌ Invalid branch name. The branch name must start with 'feature/'"
+            exit 1
+          fi
+          echo "✅ The branch name is correct: $branch_name"
+
+      - name: Check source branch on pull request
+        if: github.event_name == 'pull_request'
+        run: |
+          branch_name="${{ github.head_ref }}"
+          echo "🔍 Checking the branch: $branch_name"
+          if [[ "$branch_name" == "test" ]]; then
+            echo "❌ DENIED: You cannot send PR from test to main."
+            exit 1
+          fi
+          echo "✅ The branch is allowed: $branch_name"
+
 
   deploy:
     needs: test
